'use strict';

/**
 * Standalone openclaw launcher.
 *
 * This CJS entry point is the root of the pkg-packaged executable. It:
 *   1. Determines the directory that contains the running executable.
 *   2. Redirects openclaw's state and config storage to that same directory
 *      (via OPENCLAW_STATE_DIR / OPENCLAW_CONFIG_PATH), so the user does not
 *      need to touch ~/.openclaw at all.
 *   3. Sets process.argv[1] to the bundle path so that openclaw's internal
 *      isMainModule() check treats the bundle as the main entry point.
 *   4. Requires the pre-bundled openclaw entry (generated by the build step),
 *      which is a CJS bundle of all openclaw internal dist files.
 */

const path = require('path');

// ---------------------------------------------------------------------------
// Resolve the "home directory" for this standalone installation.
// When running as a pkg-packaged binary process.pkg is set and the real
// executable lives at process.execPath.  In development (plain `node`) we
// fall back to the project root (one level above /src).
// ---------------------------------------------------------------------------
const executableDir = process.pkg
  ? path.dirname(process.execPath)
  : path.resolve(__dirname, '..');

// ---------------------------------------------------------------------------
// Tell openclaw to store all its state (config, database, etc.) next to the
// executable instead of in ~/.openclaw.  Only set the variables if the user
// has not already provided an explicit override.
// ---------------------------------------------------------------------------
if (!process.env.OPENCLAW_STATE_DIR) {
  process.env.OPENCLAW_STATE_DIR = executableDir;
}
if (!process.env.OPENCLAW_CONFIG_PATH) {
  process.env.OPENCLAW_CONFIG_PATH = path.join(executableDir, 'openclaw.json');
}

// ---------------------------------------------------------------------------
// openclaw's dist/entry.js performs an isMainModule() guard that compares
// import.meta.url with process.argv[1].  In the CJS bundle, import.meta.url
// is replaced with pathToFileURL(__filename).href, which points to the bundle
// file (openclaw-bundle.cjs).  We set process.argv[1] to that same path so
// the check returns true and the CLI is actually invoked.
// ---------------------------------------------------------------------------
const bundlePath = require.resolve('./openclaw-bundle.cjs');
process.argv[1] = bundlePath;

// ---------------------------------------------------------------------------
// Load the pre-built CJS bundle of openclaw's internal dist files.
// This bundle is generated during the build step by esbuild from
// node_modules/openclaw/dist/entry.js.  External npm packages are required
// at runtime (resolved from the pkg snapshot).
// ---------------------------------------------------------------------------
require('./openclaw-bundle.cjs');
